# Provisions a new rented client instance of the BarberShop stack
# (sprint12072026license §5). Generates, under deploy/clients/<slug>/:
#
#   .env                      — instance config with UNIQUE crypto secrets
#   docker-compose.client.yml — override: API hardening + email + Caddy TLS edge
#   Caddyfile                 — automatic HTTPS reverse proxy for the domain
#   README-DEPLOY.md          — step-by-step deploy/update/restore runbook
#
# The portfolio demo stack is untouched: everything here is opt-in files the
# client host consumes with `docker compose -f ... -f ... --profile client`.
#
# Usage example:
#   .\deploy\new-client.ps1 -ShopName "Navalha de Ouro" -Domain "navalha.example.com" `
#       -ContactEmail "dono@navalha.example.com" -TimeZone "America/Sao_Paulo" -DefaultLocale pt-BR

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)] [string] $ShopName,
    [Parameter(Mandatory = $true)] [string] $Domain,
    [Parameter(Mandatory = $true)] [string] $ContactEmail,

    # IANA timezone id the API's ShopClock uses for shop-local business hours.
    [string] $TimeZone = 'America/Sao_Paulo',

    # Locale served WITHOUT a URL prefix (build-time route strategy).
    [ValidateSet('en', 'pt-BR')] [string] $DefaultLocale = 'pt-BR',

    [string] $ShopAddress = '',
    [string] $ShopPhone = '',

    # SMTP is all-or-none: when omitted the API safely logs emails instead of
    # sending (same fallback the demo uses).
    [string] $SmtpHost = '',
    [int]    $SmtpPort = 587,
    [string] $SmtpUser = '',
    [string] $SmtpPassword = '',

    # Defaults to deploy/clients/<domain-slug> next to this script.
    [string] $OutputDir = ''
)

$ErrorActionPreference = 'Stop'

# ── Validation ───────────────────────────────────────────────────────────────

if ($Domain -notmatch '^(?=.{4,253}$)([a-z0-9](-?[a-z0-9])*\.)+[a-z]{2,}$') {
    throw "Domain '$Domain' is not a valid lowercase DNS name (e.g. barbearia.example.com)."
}
if ($ContactEmail -notmatch '^[^\s@]+@[^\s@]+\.[^\s@]+$') {
    throw "ContactEmail '$ContactEmail' is not a valid email address."
}
$smtpFields = @($SmtpHost, $SmtpUser, $SmtpPassword) | Where-Object { $_ }
if ($smtpFields.Count -gt 0 -and $smtpFields.Count -lt 3) {
    throw 'SMTP settings are all-or-none: provide SmtpHost, SmtpUser and SmtpPassword together (or none to log emails instead of sending).'
}
$emailEnabled = if ($smtpFields.Count -eq 3) { 'true' } else { 'false' }

# ── Secret generation (unique per run, crypto RNG) ───────────────────────────

function New-RandomBytes([int] $Count) {
    $bytes = New-Object byte[] $Count
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return $bytes
}

# Base64: no '$' (compose interpolation) nor ';'/quotes (connection strings).
$jwtKey = [Convert]::ToBase64String((New-RandomBytes 64))

# SQL Server policy needs 3 of 4 character classes; the charset avoids every
# character that is special to compose (${}), connection strings (;'") or
# bash ($`\). One char of each mandatory class is guaranteed by construction.
function New-SaPassword {
    $upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ'
    $lower = 'abcdefghjkmnpqrstuvwxyz'
    $digit = '23456789'
    $symbol = '!@#_-'
    $all = $upper + $lower + $digit + $symbol
    $pick = {
        param($set)
        $idx = [BitConverter]::ToUInt32((New-RandomBytes 4), 0) % $set.Length
        $set[$idx]
    }
    $chars = @((& $pick $upper), (& $pick $lower), (& $pick $digit), (& $pick $symbol))
    for ($i = 0; $i -lt 20; $i++) { $chars += (& $pick $all) }
    -join ($chars | Sort-Object { [BitConverter]::ToUInt32((New-RandomBytes 4), 0) })
}
$saPassword = New-SaPassword

# ── Output layout ────────────────────────────────────────────────────────────

$slug = ($Domain -replace '[^a-z0-9]+', '-').Trim('-')
if (-not $OutputDir) {
    $OutputDir = Join-Path $PSScriptRoot "clients\$slug"
}
New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

$fromAddress = "noreply@$Domain"
$monogram = $ShopName.Substring(0, 1).ToUpper()

# ── .env ─────────────────────────────────────────────────────────────────────

$envContent = @'
# BarberShop rented-instance configuration for __SHOP_NAME__
# Generated by deploy/new-client.ps1 on __GENERATED_AT__.
# KEEP THIS FILE SECRET — it holds the database and JWT signing credentials.

# ── Identity / white-label ──
SHOP_NAME=__SHOP_NAME__
DOMAIN=__DOMAIN__
DEFAULT_LOCALE=__DEFAULT_LOCALE__
I18N_BASE_URL=https://__DOMAIN__
SHOP_TIMEZONE=__TIMEZONE__
NUXT_PUBLIC_SHOP_ADDRESS=__SHOP_ADDRESS__
NUXT_PUBLIC_SHOP_PHONE=__SHOP_PHONE__
NUXT_PUBLIC_SHOP_EMAIL=__CONTACT_EMAIL__

# ── Secrets (unique to this instance — never reuse the repo demo values) ──
SA_PASSWORD=__SA_PASSWORD__
JWT_KEY=__JWT_KEY__

# ── API image (pin to a released tag for reproducible deploys) ──
API_IMAGE=eduardohanacleto/barbershop-api:latest

# ── Email (Email__Enabled=false logs messages instead of sending) ──
EMAIL_ENABLED=__EMAIL_ENABLED__
SMTP_HOST=__SMTP_HOST__
SMTP_PORT=__SMTP_PORT__
SMTP_USER=__SMTP_USER__
SMTP_PASSWORD=__SMTP_PASSWORD__
EMAIL_FROM=__EMAIL_FROM__

# ── Database backups (db-backup sidecar, profile "client") ──
BACKUP_INTERVAL_MINUTES=1440
BACKUP_RETENTION=14
'@
$envContent = $envContent.
    Replace('__GENERATED_AT__', (Get-Date -Format 'yyyy-MM-dd HH:mm')).
    Replace('__SHOP_NAME__', $ShopName).
    Replace('__DOMAIN__', $Domain).
    Replace('__DEFAULT_LOCALE__', $DefaultLocale).
    Replace('__TIMEZONE__', $TimeZone).
    Replace('__SHOP_ADDRESS__', $ShopAddress).
    Replace('__SHOP_PHONE__', $ShopPhone).
    Replace('__CONTACT_EMAIL__', $ContactEmail).
    Replace('__SA_PASSWORD__', $saPassword).
    Replace('__JWT_KEY__', $jwtKey).
    Replace('__EMAIL_ENABLED__', $emailEnabled).
    Replace('__SMTP_HOST__', $SmtpHost).
    Replace('__SMTP_PORT__', [string]$SmtpPort).
    Replace('__SMTP_USER__', $SmtpUser).
    Replace('__SMTP_PASSWORD__', $SmtpPassword).
    Replace('__EMAIL_FROM__', $fromAddress)
[IO.File]::WriteAllText((Join-Path $OutputDir '.env'), $envContent)

# ── docker-compose.client.yml ────────────────────────────────────────────────

$composeOverride = @'
# Instance override for __SHOP_NAME__ — generated by deploy/new-client.ps1.
# Usage (from the repo root, with this folder's .env):
#   docker compose --env-file deploy/clients/__SLUG__/.env `
#     -f docker-compose.yml -f deploy/clients/__SLUG__/docker-compose.client.yml `
#     --profile client up -d --build
#
# Requires Docker Compose >= 2.24 (uses the `!override` tag to unpublish
# nginx's host ports — Caddy becomes the only TLS edge).

services:
  api:
    environment:
      # Shop-local clock for business hours / availability.
      - Shop__TimeZone=${SHOP_TIMEZONE}
      # Hardening: portfolio conveniences are off on rented instances.
      - Swagger__Enabled=false
      - HealthChecks__DetailEnabled=false
      # Absolute links in emails (password reset, waitlist notifications).
      - Frontend__BaseUrl=https://${DOMAIN}
      - Cors__AllowedOrigins__0=https://${DOMAIN}
      # Real SMTP delivery (falls back to logging when EMAIL_ENABLED=false).
      - Email__Enabled=${EMAIL_ENABLED}
      - Email__SmtpHost=${SMTP_HOST}
      - Email__SmtpPort=${SMTP_PORT}
      - Email__SmtpUser=${SMTP_USER}
      - Email__SmtpPassword=${SMTP_PASSWORD}
      - Email__FromAddress=${EMAIL_FROM}
      - Email__FromName=${SHOP_NAME}

  # Caddy terminates TLS with automatic Let's Encrypt certificates and
  # forwards everything to the stack's internal nginx.
  caddy:
    image: caddy:2-alpine
    container_name: barbershop-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/clients/__SLUG__/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nginx
    restart: unless-stopped

  # Caddy owns the host's 80/443 — nginx stays internal-only.
  nginx:
    ports: !override []

volumes:
  caddy_data:
  caddy_config:
'@
$composeOverride = $composeOverride.Replace('__SHOP_NAME__', $ShopName).Replace('__SLUG__', $slug)
[IO.File]::WriteAllText((Join-Path $OutputDir 'docker-compose.client.yml'), $composeOverride)

# ── Caddyfile ────────────────────────────────────────────────────────────────

$caddyfile = @'
# Automatic HTTPS for __DOMAIN__ (Let's Encrypt; certificates persist in the
# caddy_data volume). Requires the DNS A/AAAA record to point at this host
# BEFORE first start, or issuance will fail and retry with backoff.
__DOMAIN__ {
    encode gzip
    reverse_proxy nginx:80
}
'@
$caddyfile = $caddyfile.Replace('__DOMAIN__', $Domain)
[IO.File]::WriteAllText((Join-Path $OutputDir 'Caddyfile'), $caddyfile)

# ── README-DEPLOY.md ─────────────────────────────────────────────────────────

$readme = @'
# Deploy runbook — __SHOP_NAME__ (__DOMAIN__)

Instance package generated by `deploy/new-client.ps1`. All commands run from
the **repository root** on the client host.

## Prerequisites
- Docker Engine + Docker Compose **>= 2.24** (the override uses `!override`).
- DNS A/AAAA record for `__DOMAIN__` pointing at this host (required for the
  automatic Let's Encrypt certificate on first start).
- This folder (`deploy/clients/__SLUG__/`) present on the host. The `.env`
  here holds the instance's secrets — never commit it or reuse demo values.

## First deploy
```powershell
docker compose --env-file deploy/clients/__SLUG__/.env `
  -f docker-compose.yml -f deploy/clients/__SLUG__/docker-compose.client.yml `
  --profile client up -d --build
```
The `--profile client` flag also starts the `db-backup` sidecar (daily backup,
14-file retention — tune via BACKUP_* in `.env`).

## Immediately after first boot
1. Sign in at `https://__DOMAIN__/staff-login` with the seeded admin
   (`admin@barbershop.com` / `Admin@123`) and **change the password right
   away** — the seed credential is public in the repository.
2. Update the admin email, register the shop's workers and services, and set
   the weekly schedule under Admin → Schedule.

## Updating the instance
```powershell
git pull                      # or check out the release tag being deployed
docker compose --env-file deploy/clients/__SLUG__/.env `
  -f docker-compose.yml -f deploy/clients/__SLUG__/docker-compose.client.yml `
  --profile client up -d --build
```

## Backups & restore
Backups are written to the `sqlserver_backups` volume as
`barbershop-<timestamp>.bak`, verified with `RESTORE VERIFYONLY` after each
run. To restore one:
```powershell
# list available backups
docker exec barbershop-sqlserver ls -1t /backups
# restore (stop the api first so nothing writes mid-restore)
docker compose stop api
docker exec barbershop-sqlserver /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "<SA_PASSWORD>" -C -Q "RESTORE DATABASE [barbershop] FROM DISK = N'/backups/<file>.bak' WITH REPLACE"
docker compose start api
```

## Notes
- Swagger and `/health/detail` are disabled on this instance
  (`Swagger__Enabled=false`, `HealthChecks__DetailEnabled=false`).
- Emails: when SMTP is not configured, the API logs message contents instead
  of sending — check `docker logs barbershop-api`.
- Legal pages are served at `/privacy` and `/terms` in both languages.
'@
$readme = $readme.Replace('__SHOP_NAME__', $ShopName).Replace('__DOMAIN__', $Domain).Replace('__SLUG__', $slug)
[IO.File]::WriteAllText((Join-Path $OutputDir 'README-DEPLOY.md'), $readme)

# ── Summary ──────────────────────────────────────────────────────────────────

Write-Host ''
Write-Host "Instance package for '$ShopName' generated at:" -ForegroundColor Green
Write-Host "  $OutputDir"
Write-Host ''
Write-Host 'Files:'
Get-ChildItem $OutputDir -Name | ForEach-Object { Write-Host "  - $_" }
Write-Host ''
Write-Host "Shop:     $ShopName (monogram '$monogram', locale $DefaultLocale, tz $TimeZone)"
Write-Host "Domain:   https://$Domain"
Write-Host "Email:    delivery $(if ($emailEnabled -eq 'true') { "via $SmtpHost" } else { 'DISABLED (logged only — no SMTP given)' })"
Write-Host ''
Write-Host 'Next: follow README-DEPLOY.md in that folder.' -ForegroundColor Yellow
